### ISSUE TITLE
Is it possible for you to make this project in HTML and JavaScript, not Java?

### ISSUE THREAD

**Issue by DaCuteRaccoon** [Ivstiv/pixelart-converter#3]
I can't install apps on my computer, so I would like if this could run in browsers. Also, I can't replicate this in a browser, because I don't know how to code in Java, just HTML JS and CSS.

**Comment by ivstiv** [comment]
Sorry but it would take considerable amount of time to rewrite this as a web app which I don't have now. Won't be able to help you :/

**Comment by DaCuteRaccoon** [comment]
It's okay. Thanks
